# Generated by Django 4.0.6 on 2022-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileaccess_remove_linkaccess_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fileaccess',
            constraint=models.UniqueConstraint(fields=('user', 'file', 'access_type'), name='user_file_type_fileaccess'),
        ),
    ]
